<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category     :  ModuleBank
 * @package      :  ModuleBank_JahanpayPayment
 *
 * @company      :  ModuleBank
 * @created by   :  Seyed Hamzeh Fazeli
 * @contact      :  www.ModuleBank.ir, support@modulebank.ir, 09160666110
 * @created on   :  15 September 2015
 * @copyright    :  Copyright (C) 2015. All rights reserved.
 * @author       :  Seyed Hamzeh Fazeli
 * @description  :  Jahanpay Gateway Payment for the component (Magento)
 */
?>
<html>
<meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl() ?>">
<body>
<div class="page-head">
    <h3><?php echo $this->__('خطایی رخ داد') ?></h3>
</div>
<p><?php echo $this->__('با عرض پوزش خطایی در روند خرید رخ داد <a href="%s">ادامه خرید</a>.', $this->getContinueShoppingUrl()) ?></p>
</body>
</html>